/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewBancoDeMidias;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import midias.Midia;

/**
 *
 * @author SABRINA
 */
public class Geral extends javax.swing.JFrame {
    ViewPodcast podcast;
    ViewFilme filme;
    ViewAudioLivro audiolivro;
    Principal inicial;
    /**
     * Creates new form Geral
     */
    public Geral(Principal inicial, ViewPodcast podcast, ViewFilme filme, ViewAudioLivro audiol) {
        initComponents();
        this.podcast = podcast;
        this.filme = filme;
        this.audiolivro = audiol;
        this.inicial = inicial;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        sair = new javax.swing.JButton();
        btnAudioLivro = new javax.swing.JButton();
        btnFilme = new javax.swing.JButton();
        btnPodcast1 = new javax.swing.JButton();
        campoBuscar = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 500, 330));

        sair.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jPanel1.add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 100, -1));

        btnAudioLivro.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btnAudioLivro.setText("AudioLivro");
        btnAudioLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAudioLivroActionPerformed(evt);
            }
        });
        jPanel1.add(btnAudioLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, 30));

        btnFilme.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btnFilme.setText("Filme");
        btnFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilmeActionPerformed(evt);
            }
        });
        jPanel1.add(btnFilme, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 100, 30));

        btnPodcast1.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btnPodcast1.setText("Podcast");
        btnPodcast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPodcast1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPodcast1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 100, 30));
        jPanel1.add(campoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 160, -1));

        buscar.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 100, -1));

        jLabel2.setFont(new java.awt.Font("The Blacklist", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mídias");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/Rainbow.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -270, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
     * Botão que atualiza tabela do audioLivro
     */
    private void btnAudioLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAudioLivroActionPerformed
        audiolivro.atualizaTabelaA(audiolivro.getBancoAudioLivro().getMidias(), jTable1);
    }//GEN-LAST:event_btnAudioLivroActionPerformed

/**
     * Botão que atualiza tabela do filme
     */
    private void btnFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilmeActionPerformed
        filme.atualizaTabela(filme.getBancoFilmes().getMidias(), jTable1);
    }//GEN-LAST:event_btnFilmeActionPerformed

/**
     * Botão que atualiza tabela do Podcast
     */
    private void btnPodcast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPodcast1ActionPerformed
       podcast.atualizaTabela(podcast.getBancoDeMidias().getMidias(), jTable1);
    }//GEN-LAST:event_btnPodcast1ActionPerformed

/**
     * Botão que retorna a tela incial
     */
    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        setVisible(false);
        inicial.setVisible(true);
    }//GEN-LAST:event_sairActionPerformed

/**
     * Botão que faz a busca por título em todas as mídias
     */
    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        try {
            String procurado = "";
            if(filme.getBancoFilmes().consultar(campoBuscar.getText()) != null){
            procurado += filme.getBancoFilmes().consultar(campoBuscar.getText()).toString(); 
            }
            if(podcast.getBancoDeMidias().consultar(campoBuscar.getText()) != null){
            procurado += "\n" + podcast.getBancoDeMidias().consultar(campoBuscar.getText()).toString();
            }
            if(audiolivro.getBancoAudioLivro().consultar(campoBuscar.getText()) != null){
            procurado += "\n" + audiolivro.getBancoAudioLivro().consultar(campoBuscar.getText()).toString();
            }
            JOptionPane.showMessageDialog(null, procurado);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Esta Mídia não Existe!");
        }
    }//GEN-LAST:event_buscarActionPerformed
    public void gerarBackground() {
        String pasta = System.getProperty("user.dir");
        jLabel1.setIcon(new ImageIcon(pasta + "/imagens/Rainbow.jpg"));

    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAudioLivro;
    private javax.swing.JButton btnFilme;
    private javax.swing.JButton btnPodcast1;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
