/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewBancoDeMidias;

import bancoDeMidias.BancoAudioLivro;
import bancoDeMidias.BancoPodcast;
import bancoDeMidias.BancoFilmes;
import javax.swing.ImageIcon;


/**
 *
 * @author vagne
 */
public class Principal extends javax.swing.JFrame {

    private BancoPodcast bancoPodcast;
    private BancoFilmes bancoFilme;
    private ViewPodcast telaDePodcast;
    private ViewFilme telaDeFilme;
    private ViewAudioLivro telaAudioLivro;
    private BancoAudioLivro bancoAudioLivro;

    public Principal() {
        initComponents();
        this.bancoPodcast = new BancoPodcast();
        this.bancoFilme = new BancoFilmes();
        this.telaDePodcast = new ViewPodcast(bancoPodcast);
        this.telaDeFilme = new ViewFilme(bancoFilme, this);
        this.bancoAudioLivro = new BancoAudioLivro();
        this.telaAudioLivro = new ViewAudioLivro(bancoAudioLivro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoFilme = new javax.swing.JButton();
        botaoPodCast = new javax.swing.JButton();
        botaoAudioLivro = new javax.swing.JButton();
        todos = new javax.swing.JButton();
        texto = new javax.swing.JLabel();
        fundoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/filme3.png"))); // NOI18N
        botaoFilme.setMaximumSize(new java.awt.Dimension(200, 75));
        botaoFilme.setMinimumSize(new java.awt.Dimension(200, 75));
        botaoFilme.setPreferredSize(new java.awt.Dimension(200, 75));
        botaoFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFilmeActionPerformed(evt);
            }
        });
        jPanel1.add(botaoFilme, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 130, 110));

        botaoPodCast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/podcast2.png"))); // NOI18N
        botaoPodCast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPodCastActionPerformed(evt);
            }
        });
        jPanel1.add(botaoPodCast, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 130, 110));

        botaoAudioLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/audiol2.png"))); // NOI18N
        botaoAudioLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAudioLivroActionPerformed(evt);
            }
        });
        jPanel1.add(botaoAudioLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 130, 110));

        todos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/folder.png"))); // NOI18N
        jPanel1.add(todos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 130, 110));

        texto.setFont(new java.awt.Font("The Blacklist", 0, 48)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setText("Banco de Mídias:");
        texto.setToolTipText("");
        jPanel1.add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 310, -1));

        fundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/background.jpg"))); // NOI18N
        jPanel1.add(fundoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 30, 790, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 630, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFilmeActionPerformed
        try {
            bancoFilme.ler("BancoFilmes.txt");
        } catch (Exception e) {
            System.out.println("Erro: " + e.getMessage());
        }

        telaDeFilme.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botaoFilmeActionPerformed

    private void botaoPodCastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPodCastActionPerformed
        try {
            bancoPodcast.ler("BancoPodcasts.txt");
        } catch (Exception e) {
            System.out.println("Erro: " + e.getMessage());
            e.printStackTrace();
        }
        telaDePodcast.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botaoPodCastActionPerformed

    private void botaoAudioLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAudioLivroActionPerformed
          try {
            bancoAudioLivro.ler("BancoAudioLivro.txt");
        } catch (Exception e) {
            System.out.println("Erro: " + e.getMessage());
        }

        telaAudioLivro.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botaoAudioLivroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    public void gerarBackground(){
        String pasta = System.getProperty("user.dir");
        fundoPrincipal.setIcon(new ImageIcon(pasta + "/imagens/background.jpg"));
        botaoFilme.setIcon(new ImageIcon(pasta + "/imagens/filmes3.png"));
        botaoPodCast.setIcon(new ImageIcon(pasta + "/imagens/podcast2.png"));
        botaoAudioLivro.setIcon(new ImageIcon(pasta + "/imagens/audioL2.png"));
        todos.setIcon(new ImageIcon(pasta + "/imagens/folder.png"));

 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAudioLivro;
    private javax.swing.JButton botaoFilme;
    private javax.swing.JButton botaoPodCast;
    private javax.swing.JLabel fundoPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel texto;
    private javax.swing.JButton todos;
    // End of variables declaration//GEN-END:variables
}
