/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewBancoDeMidias;
import bancoDeMidias.BancoAudioLivro;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import midias.AudioLivro;
import midias.Midia;


/**
 *
 * @author Rafae
 */
public class ViewAudioLivro extends javax.swing.JFrame {
    private BancoAudioLivro bancoAudioLivro;
    private String caminho;

    public String getCaminho() {
        return caminho;
    }

    public void setCaminho(String caminho) {
        this.caminho = caminho;
    }

    /**
     * Creates new form ViewAudioLivro
     * 
     * @param bancoAudioLivro
     */
    public ViewAudioLivro(BancoAudioLivro bancoAudioLivro) {
        initComponents();
        this.bancoAudioLivro = bancoAudioLivro;
        tabelaA.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                JTable target = (JTable) e.getSource();
                int row = target.getSelectedRow();

                
                String titulo = String.valueOf(target.getValueAt(row, 0));
                String descricao = String.valueOf(target.getValueAt(row, 1));
                String ano = String.valueOf(target.getValueAt(row, 2));
                String genero = String.valueOf(target.getValueAt(row, 3));
                String autores = String.valueOf(target.getValueAt(row, 4));
                String editora = String.valueOf(target.getValueAt(row, 5));
                String idioma = String.valueOf(target.getValueAt(row, 6));
                String local = String.valueOf(target.getValueAt(row, 7));
                String duracao = String.valueOf(target.getValueAt(row, 8));
                String caminho = String.valueOf(target.getValueAt(row, 9));

                campoTitulo.setText(titulo);
                campoDescricao.setText(descricao);
                campoAno.setText(ano);
                campoGenero.setText(genero);
                campoAutores.setText(autores);
                campoEditora.setText(editora);
                campoIdioma.setText(idioma);
                campoLocal.setText(local);
                campoDuracao.setText(duracao);
                campoCaminho.setText(caminho);
                
            }

            @Override
            public void mousePressed(MouseEvent e) {
              //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseReleased(MouseEvent e) {
             //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseEntered(MouseEvent e) {
             //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseExited(MouseEvent e) {
             //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        
      });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaA = new javax.swing.JTable();
        a = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoTitulo = new javax.swing.JTextField();
        campoDescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoAno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoGenero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoAutores = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoEditora = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoIdioma = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoLocal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoDuracao = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campoCaminho = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        campoPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnVoltarAudioLivro = new javax.swing.JButton();
        btnCadastrarAudioLivro = new javax.swing.JButton();
        btnExcluirAudioLivro = new javax.swing.JButton();
        btnEditarAudioLivro = new javax.swing.JButton();
        btnOrganizar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título", "Descrição", "Ano", "Gênero", "Autores", "Editora", "Idioma", "Local", "Duração", "Caminho"
            }
        ));
        tabelaA.setColumnSelectionAllowed(true);
        tabelaA.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelaA);
        tabelaA.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel2.setText("Título:");

        jLabel3.setText("Descrição:");

        jLabel4.setText("Ano:");

        jLabel5.setText("Genero:");

        jLabel6.setText("Autores:");

        jLabel7.setText("Editora:");

        jLabel8.setText("Idioma:");

        jLabel9.setText("Local:");

        campoLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLocalActionPerformed(evt);
            }
        });

        jLabel10.setText("Duração:");

        jLabel11.setText("Caminho:");

        jButton2.setText("Procurar Caminho");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel2))
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addComponent(campoTitulo)
                            .addComponent(campoAno)
                            .addComponent(campoGenero)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoAutores)
                            .addComponent(campoEditora)
                            .addComponent(campoIdioma)
                            .addComponent(campoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDuracao)
                            .addComponent(campoCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(campoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(campoCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        campoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesquisaActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnVoltarAudioLivro.setText("Voltar");
        btnVoltarAudioLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAudioLivroActionPerformed(evt);
            }
        });

        btnCadastrarAudioLivro.setText("Cadastrar");
        btnCadastrarAudioLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarAudioLivroMouseClicked(evt);
            }
        });
        btnCadastrarAudioLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAudioLivroActionPerformed(evt);
            }
        });

        btnExcluirAudioLivro.setText("Excluir");
        btnExcluirAudioLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAudioLivroActionPerformed(evt);
            }
        });

        btnEditarAudioLivro.setText("Editar");
        btnEditarAudioLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAudioLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aLayout = new javax.swing.GroupLayout(a);
        a.setLayout(aLayout);
        aLayout.setHorizontalGroup(
            aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aLayout.createSequentialGroup()
                        .addComponent(campoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aLayout.createSequentialGroup()
                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVoltarAudioLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisar)
                            .addComponent(btnCadastrarAudioLivro)
                            .addComponent(btnExcluirAudioLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarAudioLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(158, 158, 158))))
        );
        aLayout.setVerticalGroup(
            aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(campoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar)
                .addGap(44, 44, 44)
                .addComponent(btnVoltarAudioLivro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrarAudioLivro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirAudioLivro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarAudioLivro))
            .addGroup(aLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnOrganizar.setText("Organizar lista ");
        btnOrganizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(btnOrganizar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrganizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPesquisaActionPerformed

    private void campoLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLocalActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
            AudioLivro audioLivro;
        try {
            audioLivro = (AudioLivro) bancoAudioLivro.consultar(Integer.valueOf(campoPesquisa.getText()));
            exibirAudioLivro(audioLivro);
        } catch (Exception ex) {
            audioLivro = (AudioLivro) bancoAudioLivro.consultar(campoPesquisa.getText());
            try {
                exibirAudioLivro(audioLivro);
            } catch (NullPointerException e) {
                limparCampos();
                JOptionPane.showMessageDialog(null, "Não foi possível localizar o item. Tente novamente. ", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnCadastrarAudioLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarAudioLivroMouseClicked
          // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarAudioLivroMouseClicked

    private void btnVoltarAudioLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAudioLivroActionPerformed
        JFrame frame = new JFrame();
        frame.setVisible(true);
        dispose();
        new Principal().setVisible(true);
    }//GEN-LAST:event_btnVoltarAudioLivroActionPerformed

    private void btnCadastrarAudioLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAudioLivroActionPerformed
      
       AudioLivro audioLivroNovo;
       
       audioLivroNovo = new AudioLivro(campoCaminho.getText(),
               campoTitulo.getText(), 
               campoDescricao.getText(),
               Integer.parseInt(campoAno.getText()),
               campoGenero.getText(),
               campoIdioma.getText(),
               campoAutores.getText(),
               campoLocal.getText(),
               campoEditora.getText(),
               Integer.parseInt(campoDuracao.getText())
       );
       
       bancoAudioLivro.cadastrar(audioLivroNovo);
       
       try {
            bancoAudioLivro.gravar("BancoAudioLivro.txt");
        } catch (Exception ex) {
            Logger.getLogger(ViewPodcast.class.getName()).log(Level.SEVERE, null, ex);
        }
        atualizaTabelaA(bancoAudioLivro.getMidias(), tabelaA);
       
    }//GEN-LAST:event_btnCadastrarAudioLivroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      JFileChooser fileChooser = new JFileChooser();
      fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
      fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
      int result = fileChooser.showOpenDialog(this);
      if (result == JFileChooser.APPROVE_OPTION){
       File selectedFile = fileChooser.getSelectedFile();   
       setCaminho(selectedFile.getAbsolutePath());
       campoCaminho.setText(selectedFile.getAbsolutePath());
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnExcluirAudioLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAudioLivroActionPerformed
        // bancoAudioLivro.excluir(Integer.valueOf(campoID.getText()));
         atualizaTabelaA(bancoAudioLivro.getMidias(), tabelaA);
    }//GEN-LAST:event_btnExcluirAudioLivroActionPerformed

    private void btnEditarAudioLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAudioLivroActionPerformed
        AudioLivro audioLivroEditado;
       
       audioLivroEditado = new AudioLivro(campoCaminho.getText(),
               campoTitulo.getText(), 
               campoDescricao.getText(),
               Integer.parseInt(campoAno.getText()),
               campoGenero.getText(),
               campoIdioma.getText(),
               campoAutores.getText(),
               campoLocal.getText(),
               campoEditora.getText(),
               Integer.parseInt(campoDuracao.getText())
       );
       
       //bancoAudioLivro.editar(Integer.valueOf(campoID.getText()),audioLivroEditado);
       atualizaTabelaA(bancoAudioLivro.getMidias(), tabelaA);
    }//GEN-LAST:event_btnEditarAudioLivroActionPerformed

    private void btnOrganizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganizarActionPerformed
        atualizaTabelaA(bancoAudioLivro.ordenarOddEven(bancoAudioLivro), tabelaA);
    }//GEN-LAST:event_btnOrganizarActionPerformed

    
       public BancoAudioLivro getBancoAudioLivro() {
        return bancoAudioLivro;
    }

    public void setBancoAudioLivro(BancoAudioLivro bancoAudioLivro) {
        this.bancoAudioLivro = bancoAudioLivro;
    }
    
    private void exibirAudioLivro(AudioLivro audioLivro) {
        campoCaminho.setText(audioLivro.getCaminho());
        campoTitulo.setText(audioLivro.getTitulo());
        campoDescricao.setText(audioLivro.getDescricao());
        campoAno.setText(String.valueOf(audioLivro.getAno()));
        campoGenero.setText(audioLivro.getGenero());
        campoIdioma.setText(audioLivro.getIdioma());
        campoAutores.setText(audioLivro.getAutores());
        campoLocal.setText(audioLivro.getLocal());
        campoEditora.setText(audioLivro.getEditora());
        campoDuracao.setText(String.valueOf(audioLivro.getDuracao()));
    }
     
    public void limparCampos(){
        campoCaminho.setText("");
        campoTitulo.setText("");
        campoDescricao.setText("");
        campoAno.setText("");
        campoGenero.setText("");
        campoIdioma.setText("");
        campoAutores.setText("");
        campoLocal.setText("");
        campoEditora.setText("");
        campoDuracao.setText("");
    };
    
    public JTable atualizaTabelaA(List<Midia> midiaAudioLivro, JTable tabela) {

        String matriz[][] = new String[midiaAudioLivro.size()][10];
        for (int i = 0; i < midiaAudioLivro.size(); i++) {
            AudioLivro al = (AudioLivro) midiaAudioLivro.get(i);
            matriz[i][0] = String.valueOf(al.getTitulo());
            matriz[i][1] = String.valueOf(al.getDescricao());
            matriz[i][2] = String.valueOf(al.getAno());
            matriz[i][3] = String.valueOf(al.getGenero());
            matriz[i][4] = String.valueOf(al.getAutores());
            matriz[i][5] = String.valueOf(al.getEditora());
            matriz[i][6] = String.valueOf(al.getIdioma());
            matriz[i][7] = String.valueOf(al.getLocal());
            matriz[i][8] = String.valueOf(al.getDuracao());
            matriz[i][9] = String.valueOf(al.getCaminho());
        }
        tabela.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                     "Título", "Descrição", "Ano", "Genero", "Autores", "Editora", "Idioma", "Local", "Duracao", "Caminho"
                }
        ));
        return tabela;
    }
    
 public void background(){
        String pasta = System.getProperty("user.dir");
       
 }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel a;
    private javax.swing.JButton btnCadastrarAudioLivro;
    private javax.swing.JButton btnEditarAudioLivro;
    private javax.swing.JButton btnExcluirAudioLivro;
    private javax.swing.JButton btnOrganizar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltarAudioLivro;
    private javax.swing.JTextField campoAno;
    private javax.swing.JTextField campoAutores;
    private javax.swing.JTextField campoCaminho;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JTextField campoDuracao;
    private javax.swing.JTextField campoEditora;
    private javax.swing.JTextField campoGenero;
    private javax.swing.JTextField campoIdioma;
    private javax.swing.JTextField campoLocal;
    private javax.swing.JTextField campoPesquisa;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelaA;
    // End of variables declaration//GEN-END:variables
}
